// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public partial class Course
    {
        public Course()
        {
            Enrollment = new HashSet<Enrollment>();
            Instructor = new HashSet<Person>();
        }

        public int CourseId { get; set; }

        [Required(ErrorMessage = "課程標題為必填")]
        public string Title { get; set; }
        [Required(ErrorMessage = "請填寫課程評價 (1 ~ 5)")]
        [Range(1, 5, ErrorMessage = "請填寫課程評價 (1 ~ 5)")]
        public int Credits { get; set; }
        public int DepartmentId { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<Enrollment> Enrollment { get; set; }

        public virtual ICollection<Person> Instructor { get; set; }
    }
}